version: '3'
services:
    web:
        build: .
        volumes:
            - ".:/usr/app"
        ports:
            - "8010:80"
        env_file:
            - ".env"
        environment:
            - GOOGLE_API_CLIENT_ID=${GOOGLE_API_CLIENT_ID}
            - GOOGLE_API_CLIENT_SECRET=${GOOGLE_API_CLIENT_SECRET}
            - GOOGLE_API_REDIRECT_URI=${GOOGLE_API_REDIRECT_URI}
        restart: always
        command: ["npm", "start"]